# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-02 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_corp', models.BooleanField()),
                ('points', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_player_identity', to='league.Identity'),
        ),
        migrations.AddField(
            model_name='game',
            name='played_against_identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_player_id', to='league.Identity'),
        ),
        migrations.AddField(
            model_name='game',
            name='played_against_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_player', to='league.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_player', to='league.Player'),
        ),
    ]
