# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-02 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_auto_20180402_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='occured_at',
            field=models.DateField(default=None, null=True),
        ),
    ]
