# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-05 18:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0006_event_occured_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identities', to=settings.AUTH_USER_MODEL),
        ),
    ]
