# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-09 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_identity_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_corp',
        ),
        migrations.AddField(
            model_name='game',
            name='played_against_points',
            field=models.IntegerField(default=0),
        ),
    ]
