# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-11 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_auto_20180409_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='played_against_identity',
            new_name='c_identity',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='played_against_points',
            new_name='c_points',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='played_against_player',
            new_name='corp',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='identity',
            new_name='r_identity',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='points',
            new_name='r_points',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player',
            new_name='runner',
        ),
        migrations.AddField(
            model_name='identity',
            name='faction',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='is_corp',
            field=models.NullBooleanField(),
        ),
    ]
